# main.yml
# 自动构建 Apk
name: Test, Build and Release apk

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    tags:
      - v*

# 这个工作流程需要执行的任务
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    # 这个任务的步骤
    steps:
      # 拉取项目代码
      - uses: actions/checkout@v3
      # 建立 java 环境
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: "18.x"
      # 建立 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"
      # 下载项目依赖
      - run: flutter pub get
      - run: echo $ENCODED_KEYSTORE | base64 -di > android/app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
      # 打包 APK
      - run: flutter build apk --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
      # 发布到 Release
      - name: Release apk
        uses: ncipollo/release-action@v1.5.0
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.RELEASE_TOKEN }}
      # 发布到appcenter
      - name: pub to app center
        uses: akiojin/appcenter-distribute-github-action@v1.4.8
        with:
          token: 8965623c49e206c9132c672e670e074f5bf077ab
          path: "build/app/outputs/flutter-apk/app-release.apk"
          app: "CCRICE/Rice Manga"
          
